services:
  - type: web
    name: wyked-samurai-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start

  - type: static
    name: wyked-samurai-frontend
    rootDir: web
